### ISSUE TITLE
ember deploy:list - undefined is not a function

### ISSUE THREAD

**Issue by Mithrilhall** [ember-cli/ember-cli-deploy#127]
I'm using ember-cli version 0.2.3.

'ember deploy:list' gives the following error:

```
user@linux:~/test-projects/testtoazure/config > ember deploy:list
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
undefined is not a function
TypeError: undefined is not a function
    at Class.module.exports.Task.extend.run (/home/eric/test-projects/testtoazure/node_modules/ember-cli-deploy/lib/tasks/list.js:26:19)
    at Class.module.exports.run (/home/eric/test-projects/testtoazure/node_modules/ember-cli-deploy/lib/commands/list.js:19:21)
    at Class.<anonymous> (/home/eric/test-projects/testtoazure/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/home/eric/test-projects/testtoazure/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/eric/test-projects/testtoazure/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/eric/test-projects/testtoazure/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/eric/test-projects/testtoazure/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
user@linux:~/test-projects/testtoazure/config > 
```

**Comment by LevelbossMike** [comment]
do you have an index-adapter addon installed?

**Comment by LevelbossMike** [comment]
actually I ran into this myself right now. This happens when you try to run a command in an environment that is not specified in deploy.js.

I agree that this is annoying and we need to improve the error message in this case. thx for this issue.

**Comment by LevelbossMike** [comment]
closing in favor of https://github.com/LevelbossMike/ember-deploy-redis/issues/8

**Comment by leojh** [comment]
I seem to be getting this error no matter what I try even when my environment does exist (development)
