### ISSUE TITLE
Cannot find module 'ember-cli/lib/errors/silent'

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli-deploy#163]
Running any `ember <command>` (including `v`) fails, when working against `ember-cli` master.

```
jan@ubuntu:~/code/veltro$ ember v
version: 0.2.7-master-a337a1f253
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 2.3.0
npm: 2.11.3
jan@ubuntu:~/code/veltro$ ember serve
Cannot find module 'ember-cli/lib/errors/silent'
Error: Cannot find module 'ember-cli/lib/errors/silent'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jan/code/veltro/node_modules/ember-cli-deploy/lib/utilities/configuration-reader.js:4:19)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)

```

**Comment by jherdman** [comment]
This is now an issue with the just released ember-cli 1.13 :(
