### ISSUE TITLE
Unable to sync: PermanentRedirect

### ISSUE THREAD

**Issue by tomdale** [ember-cli/ember-cli-deploy#167]
I was getting a confusing error message trying to deploy my site using S3, even though I'm pretty sure I followed all of the steps in the documentation correctly.

The specific error message was:

```
ember deploy
version: 0.2.7
Built project successfully. Stored in "dist/".
Uploading assets...
Unable to sync: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at Request.extractError (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/services/s3.js:343:35)
    at Request.callListeners (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/Users/tomdale/Code/corgi-client/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

In the end, the error was caused by the fact that AWS/ember-deploy assumed the US Standard region by default. I fixed the error by adding a `region` configuration option to `deploy.js`, in my case, `us-west-2`.

```
// config/deploy.js
// ...
    "assets": {
      "type": "s3",
      "accessKeyId": "xxx",
      "secretAccessKey": "xxx",
      "bucket": "bucket-name",
      "region": "us-west-2"
    }
// ...
```

I'm mostly leaving this issue here for future Googlers, although it might be nice to either document this or provide a better error message.

**Comment by krachtstefan** [comment]
I had the weird behavior that the upload took forever to load and I fixed it the same way as you did with your issue. I added region ```eu-west-1``` and it worked like a charme. Maybe the ```region``` configuration option should be in the example on the documentation page. That may prevent others to have one of our issues.

**Comment by lukemelia** [comment]
We updated the s3 plugin to make region have no default value and be required config option, to avoid this issue for non-us-east-1 users.
