### ISSUE TITLE
Unexpected token ;

### ISSUE THREAD

**Issue by seanrucker** [ember-cli/ember-cli-deploy#336]
I'm getting an error when trying out ember-cli-deploy with a fresh ember app. I'm using ember-cli 2.2.0-beta.3

```
$ ember new foobar
$ cd foobar
$ ember install ember-cli-deploy
$ ember install ember-cli-deploy-lightning-pack
$ ember deploy
```

This is the output:

```
version: 2.2.0-beta.3
Unexpected token ;
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Class.module.exports.Task.extend._pipelineConfig (/Users/seanrucker/Development/RoverPlatform/rover/node_modules/ember-cli-deploy/lib/tasks/deploy.js:59:14)
    at Class.module.exports.Task.extend._shouldActivate (/Users/seanrucker/Development/RoverPlatform/rover/node_modules/ember-cli-deploy/lib/tasks/deploy.js:25:23)
    at Class.module.exports.Task.extend.init (/Users/seanrucker/Development/RoverPlatform/rover/node_modules/ember-cli-deploy/lib/tasks/deploy.js:9:55)
```

**Comment by yorikim** [comment]
Hi!

Did you fill params ENV.s3.bucket and ENV.s3.region in config/deploy.js? If yes, please, share deploy.js

**Comment by achambers** [comment]
Hi @seanrucker . Is this still an issue? If so, can you please post your `deploy.js` and `package.json` here for us to inspect?
