### ISSUE TITLE
ember serve, ember deploy fail with ember-cli 0.2.0

### ISSUE THREAD

**Issue by ewalti** [ember-cli/ember-cli-deploy#94]
I just ran `npm install ember-cli-deploy --save-dev`.

When trying to run `ember serve` or `ember deploy` with `ember-cli-deploy 0.4.0`, ember complains about the following:

```
Cannot find module 'glob'
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/walti/Projects/distillery/node_modules/ember-cli-deploy/lib/utilities/detect-deprecated-config.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

It seems that the `glob` dependency is not installing automatically. If I do a `npm install --save-dev glob` in my ember directory, it then works.

How does one fix this?

**Comment by lukemelia** [comment]
Seems to me that we need to move `glob` from `devDependencies` to `dependencies`. What do you think @achambers?

**Comment by ewalti** [comment]
I think that's about right @lukemelia. Just wanted to make sure. I can do a pull request if you want.

**Comment by lukemelia** [comment]
That would be great @ewalti
