### ISSUE TITLE
ember deploy:list fails

### ISSUE THREAD

**Issue by ewalti** [ember-cli/ember-cli-deploy#96]
Upon running `ember deploy:list` the following occurs:

```
Object #<Class> has no method 'list'
TypeError: Object #<Class> has no method 'list'
    at Class.module.exports.Task.extend.run (/Users/walti/Projects/distillery/node_modules/ember-cli-deploy/lib/tasks/list.js:26:19)
    at Class.module.exports.run (/Users/walti/Projects/distillery/node_modules/ember-cli-deploy/lib/commands/list.js:19:21)
    at Class.<anonymous> (/Users/walti/Projects/distillery/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/Users/walti/Projects/distillery/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/walti/Projects/distillery/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/walti/Projects/distillery/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/walti/Projects/distillery/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by ewalti** [comment]
Ah, looks like `ember-deploy-redis` and `ember-deploy-s3` didn't make it in to our update. NPM installing both fixed this issue.

**Comment by LevelbossMike** [comment]
Hi @ewalti!

I just checked a test project that uses ember-deploy-redis as index-adapter and can't reproduce this. 

What Adapter are you using?
